security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:      
                path: /logout
                target: /
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirm, role: ROLE_USER }
        - { path: ^/register/, role: ROLE_SUPERADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/list, role: ROLE_ADMIN }
        - { path: ^/karte/edit, role: ROLE_ADMIN }
        - { path: ^/karte/new, role: ROLE_ADMIN }
        - { path: ^/.*/delete, role: ROLE_ADMIN }
        - { path: ^/farbe, role: ROLE_ADMIN }
        - { path: ^/seltenheit, role: ROLE_ADMIN }
        - { path: ^/typ, role: ROLE_ADMIN }
        - { path: ^/user/promote, role: ROLE_SUPERADMIN }
        - { path: ^/user/demote, role: ROLE_SUPERADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN