home:
    pattern:  /
    defaults: { _controller: BinaerpilotenMagicBundle:Default:index }
    
user:
    resource: "@BinaerpilotenMagicBundle/Controller/UserController.php"
    type: annotation
typ:
    resource: "@BinaerpilotenMagicBundle/Controller/TypController.php"
    type: annotation
farbe:
    resource: "@BinaerpilotenMagicBundle/Controller/FarbeController.php"
    type: annotation 
karte:
    resource: "@BinaerpilotenMagicBundle/Controller/KarteController.php"
    type: annotation    