home:
    resource: "@BinaerpilotenMagicBundle/Controller/DefaultController.php"
    type: annotation
    
user:
    resource: "@BinaerpilotenMagicBundle/Controller/UserController.php"
    type: annotation
typ:
    resource: "@BinaerpilotenMagicBundle/Controller/TypController.php"
    type: annotation
farbe:
    resource: "@BinaerpilotenMagicBundle/Controller/FarbeController.php"
    type: annotation 
karte:
    resource: "@BinaerpilotenMagicBundle/Controller/KarteController.php"
    type: annotation    
seltenheit:
    resource: "@BinaerpilotenMagicBundle/Controller/SeltenheitController.php"
    type: annotation
kartefilter:
    resource: "@BinaerpilotenMagicBundle/Controller/KarteFilterController.php"
    type: annotation
edition:
    resource: "@BinaerpilotenMagicBundle/Controller/EditionController.php"
    type: annotation
batch:
    resource: "@BinaerpilotenMagicBundle/Controller/BatchController.php"
    type: annotation
batchitem:
    resource: "@BinaerpilotenMagicBundle/Controller/BatchItemController.php"
    type: annotation