services:
    magic_user.registration.form.type:
        class: Binaerpiloten\MagicBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: magic_user_registration }
    magic_user.profile.form.type:
        class: Binaerpiloten\MagicBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: magic_user_profile }
            
    binaerpiloten.twig.token_extension:
        class: Binaerpiloten\MagicBundle\Twig\TokenExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
    binaerpiloten.twig.dragdropjs_extension:
        class: Binaerpiloten\MagicBundle\Twig\DragDropJSExtension
        arguments: [  ]
        tags:
            - { name: twig.extension }
    binaerpiloten.twig.dragdropcss_extension:
        class: Binaerpiloten\MagicBundle\Twig\DragDropCSSExtension
        arguments: [  ]
        tags:
            - { name: twig.extension }
    binaerpiloten.twig.menuButton_extension:
        class: Binaerpiloten\MagicBundle\Twig\MenuButtonExtension
        arguments: [ @router ]
        tags:
            - { name: twig.extension }            